trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Installer Node.js à partir de nvm
- script: |
    echo "##[group]Install Node.js"
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    source ~/.nvm/nvm.sh
    nvm install 20.11.0
    node -v
    npm -v
    echo "##[endgroup]"
  displayName: 'Install Node.js'

# Installer les dépendances npm avec l'option --legacy-peer-deps
- script: |
    npm install --legacy-peer-deps
  displayName: 'Install dependencies'

# Construire l'application Angular
- script: |
    npm run build -- --configuration production
  displayName: 'Build Angular application'

# Publier les artefacts de build
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/optisage-angular'  # Chemin vers les artefacts de build Angular
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'